name: Deliver Tokens To Consumer

on:
  push:
    paths:	
      - 'output/**'

jobs:
  # Add a job for every additional consumer/application
  deliver_to_react_application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deliver Platform Deliverable To Application
      uses: andstor/copycat-action@v3
      with:
        # See documentation: https://docs.github.com/e n/actions/reference/encrypted-secrets
        # Set the secret in the "src" repository
        personal_token: ${{ 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 }}
        # This is the branch that has the code for this article
        src_branch: generating-design-token-theme-shades-with-style-dictionary
        src_path: output/scss/_variables.css
        dst_owner: ashleylimin
        dst_repo_name: consume-style-dictionary-github-actions
        dst_repo_name: design-token-theme-shades
        dst_branch: main
        dst_branch: implement-shades
        dst_path: tokens/_variables.css
        username: ashleylimin
        email: ashleylimin20@gmail.com
        commit_message: Update platform deliverable
